version: "3.4"

services:
  sapindale:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sapindale:prod
    networks:
      access-platform:
        ipv4_address: 172.30.0.8
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
networks:
  access-platform:
    external: true
