version: "3.4"

services:
  sapindale:
    build:
      context: .
      target: dev
    image: sapindale:dev
    networks:
      access-platform:
        ipv4_address: 172.30.0.8
    volumes:
      - ./src:/sapindale/src
      - ./static:/sapindale/static
    environment:
      NODE_ENV: development
      PORT: 8080
networks:
  access-platform:
    external: true
