FROM node:14.19.3-alpine3.16

ENV NODE_ENV production
WORKDIR /sapindale
RUN chown -R node:node .
USER node

COPY --chown=node:node package.json package-lock.json webpack.config.js ./
RUN npm ci --also=dev

COPY --chown=node:node static ./static/
COPY --chown=node:node src ./src/

EXPOSE 8080

RUN npm run build
CMD node __sapper__/build
