version: "3.4"

services:
  sapindale:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sapindale:dev
    networks:
      access-platform:
        ipv4_address: 172.30.0.8
    volumes:
      - ./src:/sapindale/src
      - ./static:/sapindale/static
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
networks:
  access-platform:
    external: true
