FROM node:14-alpine

ENV NODE_ENV production
WORKDIR /sapindale
RUN chown -R node:node .
USER node

COPY --chown=node:node package.json package-lock.json webpack.config.js ./
RUN npm ci

COPY --chown=node:node static ./static/
COPY --chown=node:node src ./src/

EXPOSE 8080

CMD npm run build && node __sapper__/build
