version: "3.4"

services:
  sapindale:
    build:
      context: .
      target: prod
    image: sapindale:latest
    networks:
      access-platform:
        ipv4_address: 172.30.0.8
networks:
  access-platform:
    external: true
